### ISSUE TITLE
Salesforce connected app setup

### ISSUE THREAD

**Issue by alpeshvmodi** [TrueSparrowSystems/AI-SalesSparrow-API#1]
Tasks:
- [ ] Setup salesforce app with needed scope for the rest api access.
- [ ] Document salesforce app setup

**Comment by AMAN-BARBARIA** [comment]
- [ ] Setup salesforce app with needed scope for the rest api access. 
- [ ] Document salesforce app setup

**Comment by AMAN-BARBARIA** [comment]
This task is required for the completion of user story - https://github.com/TrueSparrowSystems/AI-SalesBridge-iOS-App/issues/3
